---
languages:

  # === SOURCE FILES === #

  - name: Python
    extensions: [.py]
    comment_marker: '#'
    # NOTE: Disable multiline support for Python
    # Adding at the top can interfere with module docstrings
    # multiline_start: '"""'
    # multiline_end: '"""'

  - name: C / C++
    extensions: [.h, .c, .cpp]
    comment_marker: //
    multiline_start: /*
    multiline_end: '*/'

  - name: Java/JavaScript/Groovy
    extensions: [.java, .js, .ts, .groovy]
    comment_marker: //
    multiline_start: /*
    multiline_end: '*/'

  # === SHELL SCRIPTS === #

  - name: Linux shell
    extensions: [.sh, .bash, .ps1, .tcl, .csh, .cshrc]
    comment_marker: '#'

  - name: Windows Shell
    extensions: [.bat, .cmd]
    comment_marker: '::'

  # === CI/BUILD&TEST-RELATED === #

  - name: Jenkinsfile
    extensions: ['']
    filename_pattern: '[Jj]enkinsfile(?:_.*)?'
    comment_marker: //
    multiline_start: /*
    multiline_end: '*/'

  - name: CMake
    extensions: [.cmake]
    comment_marker: '#'

  - name: CMakeLists
    extensions: [.txt]
    filename_pattern: CMakeLists
    comment_marker: '#'

  - name: Conanfile
    extensions: [.txt]
    filename_pattern: .*conanfile.*
    comment_marker: '#'

  - name: Input files
    extensions: [.in]
    comment_marker: '#'

  - name: Pip requirements
    extensions: [.txt]
    filename_pattern: .*(?:[Rr]equirements|[Cc]onstraints)
    comment_marker: '#'

  - name: CODEOWNERS
    extensions: ['']
    filename_pattern: CODEOWNERS
    comment_marker: '#'

  - name: Dotfiles
    extensions: ['']
    filename_pattern: .gitmodules
    comment_marker: '#'

  # === OTHER CONFIGS === #

  - name: YAML
    extensions: [.yaml, .yml]
    comment_marker: '#'

  - name: TOML
    # Different from YAML because does not require document start marker ('---')
    extensions: [.toml]
    comment_marker: '#'

  - name: Config
    extensions: [.cfg, .ini]
    comment_marker: '#'

  # === DOCUMENTATION / HUMAN-READABLE === #

  - name: Markdown
    extensions: [.md]
    comment_marker: <!---
    single_line_end: '--->'
    multiline_start: <!---
    multiline_end: '--->'
